In [1]:
from urllib.request import urlopen
from bs4 import BeautifulSoup

import pandas as pd

In [2]:
%pylab inline
import numpy as np
import pandas as pd
from tabulate import tabulate
import os
from ipypublish import nb_setup
from IPython.display import Image

Populating the interactive namespace from numpy and matplotlib

#  제2장

## <font color=blue> 1. 주택거래 실거래가 데이터 입수하기

### 1.1.1 공공데이타포털(DATA.GO.KR)

* 아파트매매 실거래가 상세 자료를 API를 통해서 입수하기

In [1]:
from urllib.request import urlopen
import pandas as pd
from bs4 import BeautifulSoup

ServiceKey = "PQHpCPO8XCUXCPOF7nf1CW1ue7o92cGPp5Wurd%2F8Dc370C7cl2U3K%2F9MiRRWvDANczMiUiDNHyIPA%2F92YqiK9A%3D%3D"
month = 202106
gu_code = 11650
numOfRows=1000

url = "http://openapi.molit.go.kr:8081/OpenAPI_ToolInstallPackage/service/rest/RTMSOBJSvc/getRTMSDataSvcAptTrade?LAWD_CD="+str(gu_code)+"&DEAL_YMD="+str(month)+"&numOfRows="+str(numOfRows)+"&serviceKey="+str(ServiceKey)

result = urlopen(url) #this is for response of XML
house = BeautifulSoup(result, 'lxml-xml')
te=house.find_all("item")
print(te[0])

IndexError: list index out of range

In [4]:
result.status

200

In [6]:
te[0]

<item><거래금액>     150,000</거래금액><거래유형> </거래유형><건축년도>1988</건축년도><년>2021</년><법정동> 방배동</법정동><아파트>방배임광</아파트><월>6</월><일>1</일><전용면적>82.34</전용면적><중개사소재지> </중개사소재지><지번>1010-1</지번><지역코드>11650</지역코드><층>1</층><해제사유발생일> </해제사유발생일><해제여부> </해제여부></item>

In [7]:
k = len(te)

In [8]:
k

196

In [9]:
price = te[0].거래금액.string.strip()

In [10]:
price

'150,000'

In [11]:
data = []

for i in range(k):
    price = te[i].거래금액.string.strip()
    data.append(price)

In [12]:
data

['150,000',
 '155,000',
 '290,000',
 '210,000',
 '175,000',
 '305,000',
 '44,900',
 '169,000',
 '113,000',
 '47,000',
 '177,000',
 '220,000',
 '229,000',
 '270,000',
 '234,000',
 '154,500',
 '88,000',
 '230,000',
 '230,000',
 '169,000',
 '240,000',
 '176,500',
 '178,000',
 '45,000',
 '208,750',
 '180,000',
 '110,000',
 '216,000',
 '298,500',
 '190,000',
 '155,000',
 '220,000',
 '236,000',
 '230,000',
 '230,000',
 '184,000',
 '250,000',
 '113,000',
 '118,500',
 '168,500',
 '152,500',
 '275,000',
 '175,000',
 '228,000',
 '235,000',
 '173,000',
 '225,000',
 '225,000',
 '100,000',
 '87,000',
 '110,000',
 '89,000',
 '96,000',
 '64,500',
 '89,000',
 '57,500',
 '135,000',
 '135,000',
 '119,000',
 '172,000',
 '177,000',
 '181,000',
 '71,000',
 '37,000',
 '155,000',
 '139,500',
 '197,941',
 '215,000',
 '163,000',
 '249,000',
 '249,000',
 '165,000',
 '230,000',
 '178,500',
 '189,000',
 '305,000',
 '340,000',
 '360,000',
 '306,000',
 '188,500',
 '105,000',
 '272,000',
 '200,000',
 '267,500',
 '284,500',
 '230,000',
 '170,000',
 '205,000',
 '210,000',
 '191,500',
 '199,000',
 '293,000',
 '221,000',
 '368,000',
 '294,000',
 '235,000',
 '290,000',
 '204,000',
 '175,000',
 '220,000',
 '270,000',
 '230,000',
 '294,000',
 '324,000',
 '317,000',
 '320,000',
 '195,000',
 '278,000',
 '304,000',
 '270,000',
 '110,000',
 '293,000',
 '222,000',
 '510,000',
 '126,900',
 '251,000',
 '222,000',
 '222,000',
 '375,000',
 '260,000',
 '270,000',
 '275,000',
 '420,000',
 '300,000',
 '260,000',
 '300,000',
 '452,000',
 '398,000',
 '270,000',
 '458,000',
 '305,000',
 '291,000',
 '245,000',
 '222,500',
 '358,500',
 '247,000',
 '352,000',
 '250,000',
 '42,500',
 '155,000',
 '42,000',
 '235,000',
 '31,700',
 '85,000',
 '35,500',
 '300,000',
 '29,600',
 '122,000',
 '126,800',
 '31,000',
 '279,000',
 '21,000',
 '320,000',
 '315,000',
 '135,500',
 '345,000',
 '320,000',
 '42,000',
 '24,000',
 '288,000',
 '32,000',
 '31,000',
 '47,000',
 '214,000',
 '179,000',
 '32,000',
 '168,500',
 '89,000',
 '250,000',
 '136,500',
 '19,000',
 '40,000',
 '250,000',
 '225,000',
 '150,000',
 '180,000',
 '238,500',
 '244,000',
 '295,000',
 '30,500',
 '295,000',
 '196,000',
 '233,000',
 '320,000',
 '172,000',
 '91,000',
 '33,200',
 '248,000',
 '320,000',
 '165,000',
 '137,500',
 '147,000',
 '160,000',
 '192,500',
 '192,500',
 '185,000']

In [13]:
te[0]

<item><거래금액>     150,000</거래금액><거래유형> </거래유형><건축년도>1988</건축년도><년>2021</년><법정동> 방배동</법정동><아파트>방배임광</아파트><월>6</월><일>1</일><전용면적>82.34</전용면적><중개사소재지> </중개사소재지><지번>1010-1</지번><지역코드>11650</지역코드><층>1</층><해제사유발생일> </해제사유발생일><해제여부> </해제여부></item>

In [14]:
data = []

for i in range(len(te)):
    
    price = te[i].거래금액.string.strip()
    built_yr = te[i].건축년도.string.strip()
    
    trade_yr = te[i].년.string.strip()
    trade_mon = te[i].월.string.strip()
    trade_day = te[i].일.string.strip()
                
    dong_name = te[i].법정동.string.strip()
    apt_name = te[i].아파트.string.strip()
    size = te[i].전용면적.string.strip()
    gu_code = te[i].지역코드.string.strip()

    total = [trade_yr, trade_mon, trade_day, price, built_yr, dong_name, apt_name, size, gu_code]
    data.append(total)

In [15]:
data

[['2021', '6', '1', '150,000', '1988', '방배동', '방배임광', '82.34', '11650'],
 ['2021',
  '6',
  '1',
  '155,000',
  '2003',
  '방배동',
  '삼환나띠르빌(1002-9)',
  '148.99',
  '11650'],
 ['2021', '6', '2', '290,000', '1983', '방배동', '방배신삼호', '185.46', '11650'],
 ['2021', '6', '2', '210,000', '2006', '방배동', '롯데캐슬헤론', '169.08', '11650'],
 ['2021', '6', '2', '175,000', '1992', '방배동', '대우(효령)', '84.91', '11650'],
 ['2021', '6', '3', '305,000', '2009', '방배동', '방배롯데캐슬로제', '172.27', '11650'],
 ['2021', '6', '3', '44,900', '2004', '방배동', '한신트리플', '39.31', '11650'],
 ['2021', '6', '3', '169,000', '2010', '방배동', '리첸시아방배', '134.22', '11650'],
 ['2021', '6', '5', '113,000', '2002', '방배동', '서초이에스에이3차', '59.4', '11650'],
 ['2021', '6', '5', '47,000', '2004', '방배동', '한신트리플', '43.93', '11650'],
 ['2021', '6', '6', '177,000', '1992', '방배동', '대우(효령)', '84.91', '11650'],
 ['2021', '6', '8', '220,000', '2001', '방배동', '나스빌', '243.34', '11650'],
 ['2021', '6', '10', '229,000', '2004', '방배동', '방배아크로리버', '124.569', '11650'],
 ['2021', '6', '10', '270,000', '2002', '방배동', '렉스빌', '243.25', '11650'],
 ['2021', '6', '10', '234,000', '2013', '방배동', '롯데캐슬아르떼', '121.6356', '11650'],
 ['2021',
  '6',
  '11',
  '154,500',
  '2006',
  '방배동',
  'SK리더스뷰(파스텔시티)',
  '84.83',
  '11650'],
 ['2021', '6', '12', '88,000', '2019', '방배동', '방배마에스트로', '35.53', '11650'],
 ['2021', '6', '12', '230,000', '1999', '방배동', '영지아트빌라', '243.15', '11650'],
 ['2021', '6', '12', '230,000', '1999', '방배동', '영지아트빌라', '243.15', '11650'],
 ['2021', '6', '12', '169,000', '1999', '방배동', '방배1차현대홈타운', '59.94', '11650'],
 ['2021', '6', '12', '240,000', '1999', '방배동', '방배1차현대홈타운', '114.78', '11650'],
 ['2021', '6', '12', '176,500', '1992', '방배동', '대우(효령)', '84.91', '11650'],
 ['2021', '6', '12', '178,000', '1992', '방배동', '대우(효령)', '84.91', '11650'],
 ['2021', '6', '12', '45,000', '2003', '방배동', '아이리스', '42.24', '11650'],
 ['2021', '6', '12', '208,750', '2003', '방배동', '방배신동아럭스빌', '164.79', '11650'],
 ['2021', '6', '14', '180,000', '1992', '방배동', '대우(효령)', '84.91', '11650'],
 ['2021', '6', '15', '110,000', '2004', '방배동', '프리우스', '73.25', '11650'],
 ['2021', '6', '15', '216,000', '1982', '방배동', '신동아', '102.65', '11650'],
 ['2021', '6', '16', '298,500', '1983', '방배동', '방배신삼호', '164.55', '11650'],
 ['2021', '6', '16', '190,000', '1985', '방배동', '임광', '84.78', '11650'],
 ['2021', '6', '18', '155,000', '2003', '방배동', '신호나이스빌', '147.75', '11650'],
 ['2021', '6', '19', '220,000', '1985', '방배동', '임광', '136.38', '11650'],
 ['2021', '6', '19', '236,000', '1983', '방배동', '방배신삼호', '105.04', '11650'],
 ['2021', '6', '19', '230,000', '2013', '방배동', '롯데캐슬아르떼', '84.9145', '11650'],
 ['2021', '6', '21', '230,000', '2013', '방배동', '롯데캐슬아르떼', '84.9145', '11650'],
 ['2021', '6', '23', '184,000', '1992', '방배동', '대우(효령)', '84.93', '11650'],
 ['2021', '6', '24', '250,000', '2003', '방배동', '대림e-편한세상1', '164.25', '11650'],
 ['2021', '6', '24', '113,000', '2003', '방배동', '효산빌라트', '83.95', '11650'],
 ['2021', '6', '24', '118,500', '2004', '방배동', '프리우스', '75.32', '11650'],
 ['2021', '6', '25', '168,500', '1975', '방배동', '삼호1동~3동', '81.39', '11650'],
 ['2021', '6', '26', '152,500', '2003', '방배동', '삼성래미안1', '59.9', '11650'],
 ['2021', '6', '26', '275,000', '2004', '방배동', '동부센트레빌', '134.04', '11650'],
 ['2021', '6', '26', '175,000', '2003', '방배동', '삼성래미안1', '84.91', '11650'],
 ['2021', '6', '27', '228,000', '2003', '방배동', '방배다움샤인힐', '208.85', '11650'],
 ['2021', '6', '28', '235,000', '1981', '방배동', '삼익', '151.54', '11650'],
 ['2021', '6', '28', '173,000', '2003', '방배동', '삼성래미안1', '84.91', '11650'],
 ['2021', '6', '28', '225,000', '2001', '방배동', '나스빌', '243.34', '11650'],
 ['2021', '6', '30', '225,000', '2001', '방배동', '나스빌', '243.34', '11650'],
 ['2021', '6', '30', '100,000', '2007', '방배동', '방배아크로타워', '60.12', '11650'],
 ['2021', '6', '1', '87,000', '2003', '양재동', '비젼아파트101동', '102.46', '11650'],
 ['2021', '6', '11', '110,000', '1991', '양재동', '우성', '73.15', '11650'],
 ['2021', '6', '12', '89,000', '2002', '양재동', '양재테크노2차', '80.9', '11650'],
 ['2021', '6', '12', '96,000', '2001', '양재동', '경희궁', '81.75', '11650'],
 ['2021', '6', '17', '64,500', '2002', '양재동', '누리빌', '71.48', '11650'],
 ['2021', '6', '18', '89,000', '2001', '양재동', '리치스', '84.74', '11650'],
 ['2021', '6', '19', '57,500', '2002', '양재동', '대흥', '56.65', '11650'],
 ['2021', '6', '5', '135,000', '1995', '우면동', '동고', '77.14', '11650'],
 ['2021', '6', '8', '135,000', '2011', '우면동', '서초네이처힐7단지', '59.99', '11650'],
 ['2021', '6', '12', '119,000', '1994', '우면동', '한라', '59.98', '11650'],
 ['2021', '6', '12', '172,000', '2013', '우면동', '서초네이처힐3단지', '84.77', '11650'],
 ['2021', '6', '18', '177,000', '2013', '우면동', '서초네이처힐3단지', '84.77', '11650'],
 ['2021', '6', '18', '181,000', '2013', '우면동', '서초네이처힐6단지', '114.98', '11650'],
 ['2021', '6', '23', '71,000', '2013', '우면동', '엘에이치서초4단지', '59.93', '11650'],
 ['2021', '6', '25', '37,000', '2014', '우면동', '계룡리슈빌S', '30.015', '11650'],
 ['2021', '6', '26', '155,000', '2012', '우면동', '서초힐스', '74.96', '11650'],
 ['2021', '6', '27', '139,500', '2011', '우면동', '서초네이처힐7단지', '59.99', '11650'],
 ['2021', '6', '1', '197,941', '2000', '잠원동', '노블레스', '152.01', '11650'],
 ['2021', '6', '1', '215,000', '2000', '잠원동', '노블레스', '152.01', '11650'],
 ['2021', '6', '1', '163,000', '1985', '잠원동', '신반포27', '53.46', '11650'],
 ['2021', '6', '2', '249,000', '1981', '잠원동', '신반포10', '76.32', '11650'],
 ['2021', '6', '2', '249,000', '1981', '잠원동', '신반포10', '76.32', '11650'],
 ['2021', '6', '2', '165,000', '1983', '잠원동', '신반포16', '52.26', '11650'],
 ['2021', '6', '3', '230,000', '1996', '잠원동', '한신타워', '84.93', '11650'],
 ['2021', '6', '3', '178,500', '1996', '잠원동', '한신타워', '59.81', '11650'],
 ['2021', '6', '5', '189,000', '1981', '잠원동', '신반포8', '52.74', '11650'],
 ['2021', '6', '5', '305,000', '1981', '잠원동', '신반포11', '110.42', '11650'],
 ['2021', '6', '7', '340,000', '2018', '잠원동', '아크로리버뷰신반포', '78.5', '11650'],
 ['2021', '6', '9', '360,000', '1983', '잠원동', '신반포17', '143.77', '11650'],
 ['2021', '6', '9', '306,000', '1978', '잠원동', '신반포2', '92.2', '11650'],
 ['2021', '6', '9', '188,500', '1997', '잠원동', '신화', '84.33', '11650'],
 ['2021', '6', '9', '105,000', '2001', '잠원동', '대우아이빌', '49.06', '11650'],
 ['2021', '6', '11', '272,000', '1979', '잠원동', '신반포4', '96.48', '11650'],
 ['2021', '6', '11', '200,000', '1981', '잠원동', '신반포10', '53.88', '11650'],
 ['2021', '6', '13', '267,500', '1979', '잠원동', '신반포4', '96.48', '11650'],
 ['2021', '6', '13', '284,500', '2016', '잠원동', '래미안신반포팰리스', '84.46', '11650'],
 ['2021', '6', '14', '230,000', '1978', '잠원동', '신반포2', '68.91', '11650'],
 ['2021', '6', '14', '170,000', '2008', '잠원동', '데뜨아르', '84.94', '11650'],
 ['2021', '6', '14', '205,000', '1993', '잠원동', '한신그린', '84.89', '11650'],
 ['2021', '6', '15', '210,000', '2003', '잠원동', '브라운스톤잠원', '84.94', '11650'],
 ['2021', '6', '15', '191,500', '2002', '잠원동', '동아', '59.92', '11650'],
 ['2021', '6', '16', '199,000', '1993', '잠원동', '현대', '84.87', '11650'],
 ['2021', '6', '16', '293,000', '2002', '잠원동', '롯데캐슬갤럭시', '151.11', '11650'],
 ['2021', '6', '17', '221,000', '1996', '잠원동', '한신타워', '84.93', '11650'],
 ['2021', '6', '17', '368,000', '2018', '잠원동', '신반포자이', '114.94', '11650'],
 ['2021', '6', '17', '294,000', '1979', '잠원동', '신반포4', '107.39', '11650'],
 ['2021', '6', '18', '235,000', '1981', '잠원동', '신반포10', '76.32', '11650'],
 ['2021', '6', '19', '290,000', '2002', '잠원동', '롯데캐슬갤럭시', '133.41', '11650'],
 ['2021', '6', '20', '204,000', '1981', '잠원동', '신반포8', '52.74', '11650'],
 ['2021', '6', '23', '175,000', '1996', '잠원동', '한신타워', '59.81', '11650'],
 ['2021', '6', '23', '220,000', '1992', '잠원동', '훼미리', '84.9', '11650'],
 ['2021', '6', '25', '270,000', '2019', '잠원동', '래미안신반포리오센트', '84.92', '11650'],
 ['2021', '6', '26', '230,000', '1993', '잠원동', '현대', '84.87', '11650'],
 ['2021', '6', '26', '294,000', '2016', '잠원동', '래미안신반포팰리스', '84.49', '11650'],
 ['2021', '6', '26', '324,000', '2018', '잠원동', '아크로리버뷰신반포', '78.48', '11650'],
 ['2021', '6', '28', '317,000', '1978', '잠원동', '신반포2', '107.31', '11650'],
 ['2021', '6', '29', '320,000', '1978', '잠원동', '신반포2', '92.2', '11650'],
 ['2021', '6', '29', '195,000', '1981', '잠원동', '신반포8', '52.74', '11650'],
 ['2021', '6', '29', '278,000', '2016', '잠원동', '래미안신반포팰리스', '84.49', '11650'],
 ['2021', '6', '7', '304,000', '2009', '반포동', '반포자이', '84.982', '11650'],
 ['2021', '6', '11', '270,000', '1974', '반포동', '에이아이디차관주택', '72.51', '11650'],
 ['2021', '6', '11', '110,000', '2002', '반포동', '태평아트', '78.6', '11650'],
 ['2021', '6', '11', '293,000', '2010', '반포동', '반포리체', '84.967', '11650'],
 ['2021',
  '6',
  '11',
  '222,000',
  '2001',
  '반포동',
  '상지리츠빌(73-2)',
  '159.45',
  '11650'],
 ['2021', '6', '11', '510,000', '2016', '반포동', '아크로리버파크', '129.97', '11650'],
 ['2021', '6', '11', '126,900', '2002', '반포동', '타운빌', '108.12', '11650'],
 ['2021', '6', '11', '251,000', '1974', '반포동', '에이아이디차관주택', '72.51', '11650'],
 ['2021',
  '6',
  '11',
  '222,000',
  '2001',
  '반포동',
  '상지리츠빌(73-2)',
  '159.45',
  '11650'],
 ['2021',
  '6',
  '11',
  '222,000',
  '2001',
  '반포동',
  '상지리츠빌(73-2)',
  '159.45',
  '11650'],
 ['2021', '6', '12', '375,000', '2016', '반포동', '아크로리버파크', '84.95', '11650'],
 ['2021', '6', '13', '260,000', '1974', '반포동', '에이아이디차관주택', '72.51', '11650'],
 ['2021',
  '6',
  '14',
  '270,000',
  '2007',
  '반포동',
  '반포2차ApelBaum',
  '243.97',
  '11650'],
 ['2021', '6', '15', '275,000', '2009', '반포동', '래미안퍼스티지', '59.89', '11650'],
 ['2021', '6', '15', '420,000', '2016', '반포동', '아크로리버파크', '112.96', '11650'],
 ['2021', '6', '16', '300,000', '2009', '반포동', '반포자이', '84.982', '11650'],
 ['2021', '6', '16', '260,000', '1974', '반포동', '에이아이디차관주택', '72.51', '11650'],
 ['2021', '6', '16', '300,000', '2009', '반포동', '반포자이', '84.943', '11650'],
 ['2021', '6', '18', '452,000', '1974', '반포동', '반포주공1단지', '106.25', '11650'],
 ['2021', '6', '19', '398,000', '2016', '반포동', '아크로리버파크', '84.95', '11650'],
 ['2021', '6', '19', '270,000', '2016', '반포동', '아크로리버파크', '59.97', '11650'],
 ['2021', '6', '19', '458,000', '2009', '반포동', '래미안퍼스티지', '135.92', '11650'],
 ['2021', '6', '20', '305,000', '2009', '반포동', '반포자이', '84.982', '11650'],
 ['2021', '6', '24', '291,000', '1974', '반포동', '에이아이디차관주택', '72.51', '11650'],
 ['2021', '6', '25', '245,000', '2005', '반포동', '프레스턴클레식', '215.06', '11650'],
 ['2021', '6', '26', '222,500', '2018', '반포동', '반포써밋', '59.9207', '11650'],
 ['2021', '6', '26', '358,500', '2016', '반포동', '아크로리버파크', '84.95', '11650'],
 ['2021', '6', '27', '247,000', '1987', '반포동', '반포미도', '84.96', '11650'],
 ['2021', '6', '29', '352,000', '2016', '반포동', '아크로리버파크', '84.97', '11650'],
 ['2021', '6', '30', '250,000', '1987', '반포동', '반포미도', '84.96', '11650'],
 ['2021', '6', '1', '42,500', '2014', '서초동', '강남아르젠', '27.64', '11650'],
 ['2021', '6', '2', '155,000', '2005', '서초동', '서초트라팰리스', '81.76', '11650'],
 ['2021', '6', '3', '42,000', '2014', '서초동', '강남아르젠', '27.64', '11650'],
 ['2021', '6', '3', '235,000', '1988', '서초동', '삼풍아파트', '79.47', '11650'],
 ['2021', '6', '7', '31,700', '2014', '서초동', '강남아르젠', '18.53', '11650'],
 ['2021', '6', '7', '85,000', '2001', '서초동', '밀라텔쉐르빌', '65.32', '11650'],
 ['2021', '6', '8', '35,500', '2003', '서초동', '서초이오빌', '43.2', '11650'],
 ['2021', '6', '9', '300,000', '2004', '서초동', '아크로비스타', '172.28', '11650'],
 ['2021', '6', '9', '29,600', '2003', '서초동', '서초이오빌', '36.66', '11650'],
 ['2021', '6', '9', '122,000', '2005', '서초동', '두산위브(1362)', '73.08', '11650'],
 ['2021',
  '6',
  '10',
  '126,800',
  '2005',
  '서초동',
  '서초동대우디오빌프라임',
  '84.97',
  '11650'],
 ['2021', '6', '12', '31,000', '2002', '서초동', '서초동삼성쉐르빌2', '35.22', '11650'],
 ['2021', '6', '12', '279,000', '2004', '서초동', '아크로비스타', '151.61', '11650'],
 ['2021',
  '6',
  '12',
  '21,000',
  '2013',
  '서초동',
  '서초중흥S-클래스(도시형생활주택)',
  '20.68',
  '11650'],
 ['2021', '6', '13', '320,000', '2017', '서초동', '서초푸르지오써밋', '120.86', '11650'],
 ['2021', '6', '13', '315,000', '1988', '서초동', '삼풍아파트', '130.73', '11650'],
 ['2021', '6', '14', '135,500', '2003', '서초동', '마샹스', '118.98', '11650'],
 ['2021', '6', '14', '345,000', '2005', '서초동', '더미켈란', '244.98', '11650'],
 ['2021', '6', '15', '320,000', '2017', '서초동', '서초푸르지오써밋', '120.86', '11650'],
 ['2021', '6', '15', '42,000', '2003', '서초동', '래미안서초유니빌', '45.255', '11650'],
 ['2021',
  '6',
  '16',
  '24,000',
  '2013',
  '서초동',
  '한라비발디스튜디오193',
  '19.99',
  '11650'],
 ['2021',
  '6',
  '16',
  '288,000',
  '2005',
  '서초동',
  '더샾오데움(101,102동)',
  '235.579',
  '11650'],
 ['2021', '6', '16', '32,000', '2002', '서초동', '서초동삼성쉐르빌2', '35.22', '11650'],
 ['2021', '6', '16', '31,000', '2003', '서초동', '서초대우아이빌', '35.307', '11650'],
 ['2021', '6', '17', '47,000', '2003', '서초동', '대림서초리시온', '49.92', '11650'],
 ['2021', '6', '17', '214,000', '2003', '서초동', '서초래미안', '84.97', '11650'],
 ['2021', '6', '17', '179,000', '2001', '서초동', '서초금호어울림', '124.35', '11650'],
 ['2021', '6', '18', '32,000', '2014', '서초동', '강남아르젠', '18.53', '11650'],
 ['2021',
  '6',
  '18',
  '168,500',
  '2017',
  '서초동',
  '마제스타시티(힐스테이트서리풀101,102동)',
  '59.95',
  '11650'],
 ['2021', '6', '19', '89,000', '2020', '서초동', '서초블리스아파트', '52.69', '11650'],
 ['2021', '6', '19', '250,000', '2001', '서초동', '아이파크빌', '226.19', '11650'],
 ['2021', '6', '19', '136,500', '1997', '서초동', '서초한일', '59.96', '11650'],
 ['2021',
  '6',
  '19',
  '19,000',
  '2013',
  '서초동',
  '서초중흥S-클래스(도시형생활주택)',
  '20.68',
  '11650'],
 ['2021', '6', '19', '40,000', '2019', '서초동', 'DK밸리뷰시티', '23.88', '11650'],
 ['2021', '6', '19', '250,000', '2001', '서초동', '아이파크빌', '226.19', '11650'],
 ['2021', '6', '19', '225,000', '1979', '서초동', '진흥아파트', '101.32', '11650'],
 ['2021', '6', '19', '150,000', '1997', '서초동', '서초한일', '84.98', '11650'],
 ['2021', '6', '20', '180,000', '2002', '서초동', '동원베네스트아파트', '120.81', '11650'],
 ['2021', '6', '21', '238,500', '2001', '서초동', '서초삼성래미안', '150.25', '11650'],
 ['2021', '6', '21', '244,000', '1988', '서초동', '삼풍아파트', '79.47', '11650'],
 ['2021', '6', '22', '295,000', '2020', '서초동', '래미안 리더스원', '84.94', '11650'],
 ['2021', '6', '22', '30,500', '2004', '서초동', '풍림아이원플러스', '28.666', '11650'],
 ['2021', '6', '22', '295,000', '2020', '서초동', '래미안 리더스원', '84.94', '11650'],
 ['2021', '6', '22', '196,000', '1993', '서초동', '유원서초', '84.87', '11650'],
 ['2021', '6', '23', '233,000', '2004', '서초동', '아크로비스타', '137.98', '11650'],
 ['2021', '6', '25', '320,000', '1988', '서초동', '삼풍아파트', '130.23', '11650'],
 ['2021',
  '6',
  '26',
  '172,000',
  '2017',
  '서초동',
  '마제스타시티(힐스테이트서리풀101,102동)',
  '59.95',
  '11650'],
 ['2021', '6', '26', '91,000', '2002', '서초동', '서초동삼성쉐르빌2', '70.49', '11650'],
 ['2021', '6', '27', '33,200', '2014', '서초동', '강남아르젠', '18.53', '11650'],
 ['2021', '6', '28', '248,000', '2006', '서초동', '롯데캐슬클래식', '84.98', '11650'],
 ['2021', '6', '30', '320,000', '1988', '서초동', '삼풍아파트', '130.73', '11650'],
 ['2021', '6', '5', '165,000', '2014', '내곡동', '서초더샵포레', '84.81', '11650'],
 ['2021', '6', '7', '137,500', '2014', '내곡동', '서초더샵포레', '59.69', '11650'],
 ['2021', '6', '24', '147,000', '2014', '내곡동', '서초더샵포레', '59.69', '11650'],
 ['2021', '6', '28', '160,000', '2014', '내곡동', '서초더샵포레', '84.81', '11650'],
 ['2021', '6', '3', '192,500', '2014', '신원동', '서초포레스타5단지', '101.35', '11650'],
 ['2021', '6', '3', '192,500', '2014', '신원동', '서초포레스타5단지', '101.35', '11650'],
 ['2021', '6', '11', '185,000', '2014', '신원동', '서초포레스타5단지', '84.41', '11650']]

In [16]:
temp = pd.DataFrame(data, columns= ["year", "month", "day", "price", "built_yr", "dong_name", "apt_name", "size", "gu_code"])

In [17]:
temp

,year,month,day,price,built_yr,dong_name,apt_name,size,gu_code
0,2021,6,1,"150,000",1988,방배동,방배임광,82.34,11650
1,2021,6,1,"155,000",2003,방배동,삼환나띠르빌(1002-9),148.99,11650
2,2021,6,2,"290,000",1983,방배동,방배신삼호,185.46,11650
3,2021,6,2,"210,000",2006,방배동,롯데캐슬헤론,169.08,11650
4,2021,6,2,"175,000",1992,방배동,대우(효령),84.91,11650
...,...,...,...,...,...,...,...,...,...
191,2021,6,24,"147,000",2014,내곡동,서초더샵포레,59.69,11650
192,2021,6,28,"160,000",2014,내곡동,서초더샵포레,84.81,11650
193,2021,6,3,"192,500",2014,신원동,서초포레스타5단지,101.35,11650
194,2021,6,3,"192,500",2014,신원동,서초포레스타5단지,101.35,11650
195,2021,6,11,"185,000",2014,신원동,서초포레스타5단지,84.41,11650

In [18]:
temp.to_csv('house_price.csv')